# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaIE-APOD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaIE-APOD
	pod 'Alamofire'

  target 'WaIE-APODTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WaIE-APODUITests' do
    # Pods for testing
  end

end
